[package]
name = "vncproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9"
dbus = "0.9.7"
env_logger = "0.11"
image = "0.25"
log = "0.4"
thiserror = "2.0"
tokio = { version = "1.43", features = ["io-util", "net", "macros", "rt-multi-thread", "sync"] }
